test.exe : test.c object.o
	gcc -g -o test.exe object.o test.c
object.o : object.c
	gcc -g -c object.c
error.o : error.c
	gcc -g -c error.c
ku.o : ku.c
	gcc -g -c ku.c
mobian.exe : mobian.c
	gcc -g -o mobian.exe mobian.c
