#!/bin/sh
# chkconfig: 2345 50 50
# description: Poor man's remote syslog message sorter

# Source function library.
. /etc/init.d/functions

name=rxlogd
prog=/usr/bin/$name

. /etc/sysconfig/$name

start() {
	mkdir -p ${LOGDIR}/oldlogs
	chown -R ${USER}: $LOGDIR
	echo -n $"Starting $name: "
	daemon $prog -- -u $USER -l $LOGDIR -p $LISTENPORT
	ret=$?
	[ $ret -eq 0 ] && touch /var/lock/subsys/$name
	echo
	return $ret
}	

stop() {
	echo -n $"Shutting down $name: "
	killproc $prog
	ret=$?
	[ $ret -eq 0 ] && rm -f /var/lock/subsys/$name
	echo
	return $ret
}	

restart() {
	echo $"Restarting $name:"
	stop
	start
}

reopenlogs() {
	# prevent killproc from printing "[OK]" which interferes with logrotate/cron
	LSB=1 killproc $prog -HUP >/dev/null
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	status)
		status $prog
	;;
	reopenlogs)
		reopenlogs $prog
	;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|reopenlogs}"
		exit 1
esac

exit $?
